{
  "results": {
    "dockerfile": {
      "exist": false,
      "count": 0,
      "rootCount": 0,
      "subFolderCount": 0,
      "filepaths": []
    },
    "composefile": {
      "exist": false,
      "count": 0,
      "rootCount": 0,
      "subFolderCount": 0,
      "filepaths": []
    },
    "devcontainer": {
      "exist": false,
      "count": 0,
      "rootCount": 0,
      "subFolderCount": 0,
      "filepaths": []
    },
    "kustomize": {
      "exist": false,
      "count": 0,
      "rootCount": 0,
      "subFolderCount": 0,
      "filepaths": []
    },
    "helm": {
      "exist": false,
      "count": 0,
      "rootCount": 0,
      "subFolderCount": 0,
      "filepaths": []
    },
    "k8s": {
      "exist": false,
      "count": 0,
      "rootCount": 0,
      "subFolderCount": 0,
      "filepaths": []
    },
    "backstage": {
      "exist": false,
      "count": 0,
      "rootCount": 0,
      "subFolderCount": 0,
      "filepaths": []
    },
    "terraform": {
      "exist": false,
      "count": 0,
      "rootCount": 0,
      "subFolderCount": 0,
      "filepaths": []
    }
  },
  "info": {
    "id": 256143992,
    "name": "vmware_vcenter_cve_2020_3952",
    "full_name": "guardicore/vmware_vcenter_cve_2020_3952",
    "owner": {
      "login": "guardicore",
      "html_url": "https://github.com/guardicore",
      "type": "Organization"
    },
    "html_url": "https://github.com/guardicore/vmware_vcenter_cve_2020_3952",
    "description": "Exploit for CVE-2020-3952 in vCenter 6.7",
    "url": "https://api.github.com/repos/guardicore/vmware_vcenter_cve_2020_3952",
    "clone_url": "https://github.com/guardicore/vmware_vcenter_cve_2020_3952.git",
    "homepage": "https://www.guardicore.com/2020/04/pwning-vmware-vcenter-cve-2020-3952/",
    "size": 3,
    "stargazers_count": 263,
    "watchers_count": 263,
    "language": "Python"
  }
}